// output/react/src/test-component.tsx
"use client";
import * as React from "react";
import { useState } from "react";
import "./index.css";

function MyComponent(props: any) {
  const [name, setName] = useState(() => "Alex");

  return (
    <div className="bg-white flex flex-col">
      <input value={name} onChange={(event) => setName(event.target.value)} />
      Hello! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}

export default MyComponent;

// output/qwik/src/test-component.tsx
import { $, Fragment, component$, h, useStore } from "@builder.io/qwik";

export const MyComponent = component$((props: any) => {
  const state = useStore<any>({ name: "Alex" });

  return (
    <div class="bg-white flex flex-col">
      <input
        value={state.name}
        onChange$={$((event) => (state.name = event.target.value))}
      />
      Hello! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
});

export default MyComponent;
